node {

    stage('Preparation') {
        checkout scm
        //checkout([$class: 'GitSCM', branches: [[name: '*/master']],
        //   userRemoteConfigs: [[
        //      url: 'https://gitlab.com/tarent/youtrain-server.git',
        //      credentialsId: 'gitlab_tech_user']]
        //])
    }

    stage('Build') {
        echo 'Building....'
        sh './gradlew clean build'
        sh "docker build -t registry.gitlab.com/tarent/youtrain-server:$BUILD_NUMBER ."
    }

    stage('Deploy') {
        echo "Deploying registry.gitlab.com/tarent/youtrain-server:$BUILD_NUMBER"
        // in production you would most likely not use docker-compose
        // $BUILD_NUMBER is referenced in docker-compose.yml
        sh 'docker-compose up -d'
    }

    stage('Cleanup') {
        echo 'Cleanup....'
        try {
            sh 'src/bin/docker-cleanup.sh'
        } catch (Exception e) {
            echo "Warn: $e"
        }
    }

}